### ISSUE TITLE
Use more ascii characters for more efficient uft-8 encoding

### ISSUE THREAD

**Issue by KeinNiemand** [fleschutz/base256U#2]
If you want your base256 encoding to be as efficient as possible you should use every available printable ascii character. In UTF-8 Ascii character is represented in 1 byte while anything beyond ascii is 2 bytes, so using all 94 (without space) or 95 (with space) and only using Unicode characters in the alphabet after the from 95-255 or 96-255..

**Comment by fleschutz** [comment]
Yes, using more ASCII characters would be more efficient (1 byte vs 2 bytes). However, I decided against it for 2 reasons:

1.  Just small data is typically represented in Base256, e.g. 8/16/32/64/128 bytes for passwords/hashes/etc. Therefore, efficiency is not top priority.
2. Please note that non-terminal characters have been used only for Base256 to support double-clicking for copy&paste. With terminal characters (+-/*.,%&=?...) this would be much more complicated and error-prone. Just think of period or commata at the end.
